server.port=8004
spring.application.name=taskora-payment-billing-service

# Expose Spring Boot Actuator Health Probes for Kubernetes
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
